name: SLBossSpawner
version: '${project.version}'
main: dev.salyvn.slBossSpawner.SLBossSpawner
api-version: '1.21'
author: SalyVn
description: Boss spawner plugin with MythicMobs integration
softdepend: [PlaceholderAPI, MMOItems]
depend: [MythicMobs]

commands:
  slboss:
    description: Main boss spawner command
    usage: /<command> [help|reload|spawn|despawn|info|list]
    aliases: [slbs]
    permission: slboss.use

permissions:
  slboss.use:
    description: Basic command access
    default: op
  slboss.reload:
    description: Reload plugin configuration
    default: op
  slboss.spawn:
    description: Force spawn boss
    default: op
  slboss.despawn:
    description: Despawn current boss
    default: op
  slboss.info:
    description: View boss information
    default: true
  slboss.*:
    description: All permissions
    default: op
    children:
      slboss.use: true
      slboss.reload: true
      slboss.spawn: true
      slboss.despawn: true
      slboss.info: true
